
FEATURE_BLUETOOTH := false
FEATURE_WIFI := true
FEATURE_CAMERA := false
FEATURE_LOCATION_GPS := false
FEATURE_SENSOR := false
FEATURE_NFC := false
FEATURE_FINGERPRINT := false
FEATURE_MICROPHONE := true
FEATURE_TELEPHONY := false
FEATURE_USB_HOST := true
FEATURE_USB_ACCESSORY := true
