#
# Copyright (C) 2021 The Android Open-Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

### Common Part
TARGET_ARCH := riscv64
TARGET_CPU_ABI := riscv64
TARGET_ARCH_VARIANT := riscv64
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := 

BOARD_VNDK_VERSION := current

### Recovery Part
#BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
#BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true

### BOOT Part
BOARD_BOOTCONFIG += androidboot.console=ttyS0
BOARD_BOOTCONFIG += androidboot.bootreason=cold,powerkey
#BOARD_BOOTCONFIG += androidboot.usb_mode=3
#BOARD_BOOTCONFIG += androidboot.usb_speed=5

# Set by UBoot to support EMMC & SD
## androidboot.boot_devices and androidboot.slot_suffix have already been set in the bootloader. Duplicate configurations will cause errors in parsing the bootconfig.
#BOARD_BOOTCONFIG += androidboot.boot_devices=30c00000.mmc
#BOARD_BOOTCONFIG += androidboot.slot_suffix=_a

BOARD_BOOTCONFIG += androidboot.force_normal_boot=1
BOARD_BOOTCONFIG += androidboot.wificountrycode=CN
ifneq (,$(filter userdebug eng, $(TARGET_BUILD_VARIANT)))
BOARD_BOOTCONFIG += androidboot.selinux=permissive
endif

BOARD_BOOTCONFIG += androidboot.hardware=andes


BOARD_KERNEL_CMDLINE += bootconfig
BOARD_KERNEL_CMDLINE += printk.devkmsg=on
BOARD_KERNEL_CMDLINE += firmware_class.path=/vendor/lib/firmware

# Include *.dtb to vendor_boot.img and use Android Boot Image v4
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
## This is only valid when super.img enabled
BOARD_BOOT_HEADER_VERSION := 4
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
# TODO: check
BOARD_INIT_BOOT_HEADER_VERSION := 4
BOARD_MKBOOTIMG_INIT_ARGS += --header_version $(BOARD_INIT_BOOT_HEADER_VERSION)

# 43M - Check, enlarge: XC-TODO
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x8000000

# 8M
BOARD_INIT_BOOT_IMAGE_PARTITION_SIZE := 8388608

# 64M - vendor_boot.img
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864

BOARD_DTBOIMG_PARTITION_SIZE := 0x100000 # 1 MiB
# Pass unsigned dtbo image (generated by build/tasks/dtimages.mk) to Android
# build system for AVB signing
DTBO_UNSIGNED := dtbo-unsigned.img
# $(PRODUCT_OUT) hasn't been defined yet, so use "=" instead of ":="
# so that it is resolved later
BOARD_PREBUILT_DTBOIMAGE = $(PRODUCT_OUT)/$(DTBO_UNSIGNED)

# Enable dex pre-opt to speed up initial boot
WITH_DEXPREOPT := false

### Userdata partition definition
BOARD_USES_METADATA_PARTITION := true

TARGET_USERIMAGES_USE_EXT4 := true




# wlan
WIFI_HIDL_UNIFIED_SUPPLICANT_SERVICE_RC_ENTRY := true
